# Base URL
baseURL: "https://withblue.ink/"

# Ignore files
ignoreFiles:
  - "\\.sh$"
  - "Makefile"
  - "Dockerfile"

# Default language
languageCode: "en-us"

# Basic metadata
title: "With Blue Ink"
copyright: "Unless otherwise noted, all blog posts, photos, graphics, presentations and other media and assets are copyrighted work with all rights reserved. Unless otherwise noted, all code snippets are available under the Unlicense."
author: "Alessandro Segala"

# Custom params
params:
  # Enable debug views
  debugView: false
  # Enable comments
  comments: true
  # Site description
  description: "A blog by Alessandro Segala (@ItalyPaleAle)"
  # Plausible Analytics
  PlausibleAnalytics:
    Domain: withblue.ink

# Theme configuration
theme: "withblueink"
pagination:
  pagerSize: 15

# URL configuration: ensure we use ugly URLs
relativeURLs: false
canonifyURLs: false
uglyurls: true

# Format for posts' permalinks
permalinks:
  posts: /:year/:month/:day/:slug

# Disable taxonomies
disableKinds:
  - term
  - taxonomy
  - section

# RSS
rssLimit: 10
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Image pipelines
imaging:
  resampleFilter: "lanczos"

# Privacy
privacy:
  youtube:
    privacyEnhanced: true
  x:
    enableDNT: true
    simple: true

# Markup converters and syntax highlighter
markup:
  #defaultMarkdownHandler: blackFriday
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
