compatibility_date = "2021-11-08"
type = "webpack"
name = "withblueink-dev"
# Dev environment is deployed to a workers.dev domain
workers_dev = true
# Use CF_ACCOUNT_ID instead
#account_id = ""
# Use CF_ZONE_ID instead
#zone_id = ""
vars = {STORAGE_CONTAINER = "withblueink-dev", DOMAINS = "withblueink-dev.italypaleale.workers.dev", PLAUSIBLE_ANALYTICS = ""}

[site]
bucket = "./public"
entry-point = "workers-site"

[env.staging]
name = "withblueink-staging"
workers_dev = true
route = "staging.withblue.ink/*"
vars = {STORAGE_CONTAINER = "withblueink-staging", DOMAINS = "staging.withblue.ink", PLAUSIBLE_ANALYTICS = "https://pls.italypaleale.me"}

[env.production]
name = "withblueink"
workers_dev = true
route = "*withblue.ink/*"
vars = {STORAGE_CONTAINER = "withblueink-prod", DOMAINS = "withblue.ink", PLAUSIBLE_ANALYTICS = "https://pls.italypaleale.me"}
