# Purges the CDN cache

# Required secrets:
# CF_ACCOUNT_ID: Account ID for Cloudflare Workers
# CF_API_TOKEN: API token for Cloudflare (for the Workers CLI)
# CF_ZONE_ID: Zone ID for the Cloudflare domain

name: 'Purge CDN'

on:
  workflow_dispatch:

jobs:
  purge-cdn:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Purge CDN cache'
        run: |
          # Purge CDN cache
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
            -H "Authorization: Bearer ${CF_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
